---
title: "Swarmer_Transcriptomes"
author: "Iris Rizos"
date: '2022-07-28'
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include=F}
# Import packages
library(ggplot2)
library(RColorBrewer)
library(stringr)

```

# COG functional annotation categories (EggNog Mapper)

## Sample 44 = SPB

```{r, echo=F}
t44 <- read.csv("eggNOG_Mapper_on_hf44_annotations.tsv",header=T,sep="\t")

cog <- data.frame(table(t44$COG_category))
names(cog)[1] <- "COGs"
names(cog)[2] <- "Genes"

p44 <- ggplot(cog, aes(fill=COGs, y=Genes, x=COGs)) +
  geom_bar(stat="identity", colour="black") + 
  theme_bw() +
  theme(strip.text.x = element_text(color = "black", face = "bold"),
        axis.ticks.x=element_blank(), axis.title.x=element_blank(),
        axis.text.x = element_text(face = "bold", color = "purple", size = 9, angle = 45, hjust = 1)) +
  theme(legend.position = "bottom", legend.title = element_text(face="bold")) +
  geom_text(aes(label=Genes), position=position_dodge(width=0.9), vjust=-0.25) +
  ylab("Nb of nodes") +
  labs(fill='COG category') +
  ggtitle("SPB (hf44)") +
  theme(plot.title = element_text(face="bold"))

plot(p44)
```

## Sample 45 = SPC

```{r, echo=F}
t45 <- read.csv("eggNOG_Mapper_on_hf45_annotations.tsv",header=T,sep="\t")

cog <- data.frame(table(t45$COG_category))
names(cog)[1] <- "COGs"
names(cog)[2] <- "Genes"

p45 <- ggplot(cog, aes(fill=COGs, y=Genes, x=COGs)) +
  geom_bar(stat="identity", colour="black") + 
  theme_bw() +
  theme(strip.text.x = element_text(color = "black", face = "bold"),
        axis.ticks.x=element_blank(), axis.title.x=element_blank(),
        axis.text.x = element_text(face = "bold", color = "purple", size = 9, angle = 45, hjust = 1)) +
  theme(legend.position = "none") +
  geom_text(aes(label=Genes), position=position_dodge(width=0.9), vjust=-0.25) +
  ylab("Nb of nodes") +
  labs(fill='COG category') +
  ggtitle("SPC (hf45)") +
  theme(plot.title = element_text(face="bold"))

plot(p45)
```

## Sample 46 = C3

```{r, echo=F}
t46 <- read.csv("eggNOG_Mapper_on_hf46_annotations.tsv",header=T,sep="\t")

cog <- data.frame(table(t46$COG_category))
names(cog)[1] <- "COGs"
names(cog)[2] <- "Genes"

p46 <- ggplot(cog, aes(fill=COGs, y=Genes, x=COGs)) +
  geom_bar(stat="identity", colour="black") + 
  theme_bw() +
  theme(strip.text.x = element_text(color = "black", face = "bold"),
        axis.ticks.x=element_blank(), axis.title.x=element_blank(),
        axis.text.x = element_text(face = "bold", color = "purple", size = 9, angle = 45, hjust = 1)) +
  theme(legend.position = "none") +
  geom_text(aes(label=Genes), position=position_dodge(width=0.9), vjust=-0.25) +
  ylab("Nb of nodes") +
  labs(fill='COG category') +
  ggtitle("C3 (hf46)") +
  theme(plot.title = element_text(face="bold"))

plot(p46)
```

# Split multiple annotations

```{r, echo=F}
# SPB, hf 44
# Split mutliple cog annotations
  sample <- c()
  COG_1 <- c()
  COG_2 <- c()
  COG_3 <- c()
  COG_4 <- c()
  COG_5 <- c()
  for(i in 1:nrow(t44)) {
      k <- str_split_fixed(t44[i,7], "", 5) ;
      node <- c(t44[i,1]) ;
      COG_1 <- c(COG_1, paste(k[1])) ;
      COG_2 <- c(COG_2, paste(k[2])) ;
      COG_3 <- c(COG_3, paste(k[3])) ;
      COG_4 <- c(COG_4, paste(k[4])) ;
      COG_5 <- c(COG_5, paste(k[5])) ;
  }
  
# Data frame with all rows of a CC
df <- data.frame(node,COG_1,COG_2,COG_3,COG_4,COG_5)
  
# Count nodes of each cog separated category
cog1 <- data.frame(table(df$COG_1))
cog2 <- data.frame(table(df$COG_2))
cog3 <- data.frame(table(df$COG_3))
cog4 <- data.frame(table(df$COG_4))
cog5 <- data.frame(table(df$COG_5))

cogs <- rbind(cog1,cog2,cog3,cog4,cog5)

# Merge categories
cogs_agg <- aggregate(. ~ Var1, data=cogs, sum)

# Remove empty cells
cogs_agg2 <- cogs_agg[1:(nrow(cogs_agg)-1),]

names(cogs_agg2)[1] <- "COGs"
names(cogs_agg2)[2] <- "Genes"

# Plot 
p44 <- ggplot(cogs_agg2, aes(fill=COGs, y=Genes, x=COGs)) +
  geom_bar(stat="identity", colour="black") + 
  theme_bw() +
  theme(strip.text.x = element_text(color = "black", face = "bold"),
        axis.ticks.x=element_blank(), axis.title.x=element_blank(),
        axis.text.x = element_text(face = "bold", color = "black", size = 9)) +
  theme(legend.position = "none") +
  geom_text(aes(label=Genes), position=position_dodge(width=0.9), vjust=-0.25) +
  ylab("Nb of nodes") +
  labs(fill='COG category') +
  ggtitle("SPB (hf44)") +
  theme(plot.title = element_text(face="bold"))

plot(p44)
##

# SPC, hf 45
# Split mutliple cog annotations
  sample <- c()
  COG_1 <- c()
  COG_2 <- c()
  COG_3 <- c()
  COG_4 <- c()
  COG_5 <- c()
  for(i in 1:nrow(t45)) {
      k <- str_split_fixed(t45[i,7], "", 5) ;
      node <- c(t45[i,1]) ;
      COG_1 <- c(COG_1, paste(k[1])) ;
      COG_2 <- c(COG_2, paste(k[2])) ;
      COG_3 <- c(COG_3, paste(k[3])) ;
      COG_4 <- c(COG_4, paste(k[4])) ;
      COG_5 <- c(COG_5, paste(k[5])) ;
  }
  
# Data frame with all rows of a CC
df <- data.frame(node,COG_1,COG_2,COG_3,COG_4,COG_5)
  
# Count nodes of each cog separated category
cog1 <- data.frame(table(df$COG_1))
cog2 <- data.frame(table(df$COG_2))
cog3 <- data.frame(table(df$COG_3))
cog4 <- data.frame(table(df$COG_4))
cog5 <- data.frame(table(df$COG_5))

cogs <- rbind(cog1,cog2,cog3,cog4,cog5)

# Merge categories
cogs_agg <- aggregate(. ~ Var1, data=cogs, sum)

# Remove empty cells
cogs_agg2 <- cogs_agg[-c(25),]

names(cogs_agg2)[1] <- "COGs"
names(cogs_agg2)[2] <- "Genes"

# Plot 
p45 <- ggplot(cogs_agg2, aes(fill=COGs, y=Genes, x=COGs)) +
  geom_bar(stat="identity", colour="black") + 
  theme_bw() +
  theme(strip.text.x = element_text(color = "black", face = "bold"),
        axis.ticks.x=element_blank(), axis.title.x=element_blank(),
        axis.text.x = element_text(face = "bold", color = "black", size = 9)) +
  theme(legend.position = "none") +
  geom_text(aes(label=Genes), position=position_dodge(width=0.9), vjust=-0.25) +
  ylab("Nb of nodes") +
  labs(fill='COG category') +
  ggtitle("SPC (hf45)") +
  theme(plot.title = element_text(face="bold"))

plot(p45)
##

# SPC, hf 46
# Split mutliple cog annotations
  sample <- c()
  COG_1 <- c()
  COG_2 <- c()
  COG_3 <- c()
  COG_4 <- c()
  COG_5 <- c()
  for(i in 1:nrow(t46)) {
      k <- str_split_fixed(t46[i,7], "", 5) ;
      node <- c(t46[i,1]) ;
      COG_1 <- c(COG_1, paste(k[1])) ;
      COG_2 <- c(COG_2, paste(k[2])) ;
      COG_3 <- c(COG_3, paste(k[3])) ;
      COG_4 <- c(COG_4, paste(k[4])) ;
      COG_5 <- c(COG_5, paste(k[5])) ;
  }
  
# Data frame with all rows of a CC
df <- data.frame(node,COG_1,COG_2,COG_3,COG_4,COG_5)
  
# Count nodes of each cog separated category
cog1 <- data.frame(table(df$COG_1))
cog2 <- data.frame(table(df$COG_2))
cog3 <- data.frame(table(df$COG_3))
cog4 <- data.frame(table(df$COG_4))
cog5 <- data.frame(table(df$COG_5))

cogs <- rbind(cog1,cog2,cog3,cog4,cog5)

# Merge categories
cogs_agg <- aggregate(. ~ Var1, data=cogs, sum)

# Remove empty cells count
cogs_agg2 <- cogs_agg[-c(25),]

names(cogs_agg2)[1] <- "COGs"
names(cogs_agg2)[2] <- "Genes"

# Plot 
p46 <- ggplot(cogs_agg2, aes(fill=COGs, y=Genes, x=COGs)) +
  geom_bar(stat="identity", colour="black") + 
  theme_bw() +
  theme(strip.text.x = element_text(color = "black", face = "bold"),
        axis.ticks.x=element_blank(), axis.title.x=element_blank(),
        axis.text.x = element_text(face = "bold", color = "black", size = 9)) +
  theme(legend.position = "none") +
  geom_text(aes(label=Genes), position=position_dodge(width=0.9), vjust=-0.25) +
  ylab("Nb of nodes") +
  labs(fill='COG category') +
  ggtitle("C3 (hf46)") +
  theme(plot.title = element_text(face="bold"))

plot(p46)
##

```

### Major categories:

SPB:

-   S: unknown function

-   -: no match

-   J: translation



SPC:

-   Z: cytoskeleton

-   S: unknown function

-   -: no match


C3:

-   S: unknown function

-   O: post-translational modification

-   Z: cytoskeleton


# Functions of each category
